Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/xenial64'

  config.vm.define 'controller' do |c|
    c.vm.hostname = 'controller'
    c.vm.network 'private_network', ip: '10.240.0.10'
    c.vm.provision :shell, path: 'scripts/bootstrap/00-install-docker.sh'
    c.vm.provision :shell, path: 'scripts/bootstrap/01-install-k8s-tools.sh'

    c.vm.provider 'virtualbox' do |v|
      v.memory = 2048
    end
  end

  config.vm.define 'worker' do |c|
    c.vm.hostname = 'worker'
    c.vm.network 'private_network', ip: '10.240.0.20'
    c.vm.provision :shell, path: 'scripts/bootstrap/00-install-docker.sh'
    c.vm.provision :shell, path: 'scripts/bootstrap/01-install-k8s-tools.sh'
    c.vm.provider 'virtualbox' do |v|
      v.memory = 1024
    end
  end
end
