Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/xenial64'

  config.vm.define 'controller' do |c|
    c.vm.hostname = 'controller'
    c.vm.network 'private_network', ip: '10.240.0.10'
    c.vm.provision :shell, path: 'scripts/bootstrap/00-install-docker.sh'
    c.vm.provision :shell, path: 'scripts/bootstrap/01-install-k8s-tools.sh'
    c.vm.provision :shell, path: 'scripts/bootstrap/02-setup-kubelet.sh'
    c.vm.provision :shell, path: 'scripts/bootstrap/03-setup-k8s-master-node.sh'
    c.vm.provision :shell, path: 'scripts/bootstrap/04-setup-calico.sh', privileged: false

    c.vm.provider 'virtualbox' do |v|
      v.memory = 2048
    end
  end

  (0..1).each do |i|
    config.vm.define "worker-#{i}" do |c|
      c.vm.hostname = "worker-#{i}"
      c.vm.network 'private_network', ip: "10.240.0.#{i + 2}0"
      c.vm.provision :shell, path: 'scripts/bootstrap/00-install-docker.sh'
      c.vm.provision :shell, path: 'scripts/bootstrap/01-install-k8s-tools.sh'
      c.vm.provision :shell, path: 'scripts/bootstrap/02-setup-kubelet.sh'
      c.vm.provider 'virtualbox' do |v|
        v.cpus = 1
        v.memory = 1024
      end
    end
  end
end
